### ISSUE TITLE
Detect Connection Type (WiFi or Mobile Data) - Feature

### ISSUE THREAD

**Issue by jumaallan** [jumaallan/AndroidNetworkManager#3]
This would help users determine what to do depending on the connection type the phone has, like pull updates if connected to WiFi, or perform background tasks. And maybe allow basic app functionality using mobile data

**Comment by chweez** [comment]
I believe this is what was added with [this pull](https://github.com/jumadeveloper/AndroidNetworkManager/pull/1). Specifically, with `NetworkManager#isConnectedToWifi` [here](https://github.com/jumadeveloper/AndroidNetworkManager/blob/849a6c33a1a4a43d5472604e9935e1a14dd1c7e2/networkmanager/src/main/java/com/androidstudy/networkmanager/NetworkManager.java#L68) and `NetworkManager#isConnectedToMobile`  [here](https://github.com/jumadeveloper/AndroidNetworkManager/blob/849a6c33a1a4a43d5472604e9935e1a14dd1c7e2/networkmanager/src/main/java/com/androidstudy/networkmanager/NetworkManager.java#L79). But maybe i'm not getting something. Do you intend to extend the functionality?

**Comment by jumaallan** [comment]
No, I just realized that after pulling your code. To close issue, open if you need further functionality or you are missing something!
